# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go clean
    - go fmt -n -x ./...
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: The-Next-Bug 
    name: k8s-node-watcher


  prerelease: auto

  discussion_category_name: General

  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

  header: |
    ## {{.ProjectName}}-v{{.Version}} ({{ .Date }})

    Warning: This software is ALPHA quality. Use at your own risk.

