name: Build application binaries.

on:
  push:
    tags: 
      - "v*"
    # branches:
    #  - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true

      - name: GoReleaser version
        run: goreleaser -v

      - name: Run Release
        # if: startsWith(github.ref, 'refs/tags/v')
        run: goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
